name: Check Code Captains

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-code-captains:
    uses: upshift-dev/code-captains/.github/workflows/code-captains-workflow.yml@1.0.1
    secrets:
      token: ${{ secrets.CODE_CAPTAINS_CHECKING_TOKEN }}
